# Site settings
author: Alex Sanchez
title: Coffee Thoughts
header-img: img/home-bg.png
email: alexanderclaysanchez@gmail.com
copyright_name: Alex Sanchez
description: > # this means to ignore newlines until "baseurl:"
  Morning reflections on my journey, over a cup of coffee.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: alexcoldbrew
github_username:  alexcoldbrew

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
